import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="bg-white border-b">
          <div className="mx-auto max-w-7xl px-4">
            <div className="flex h-16 items-center justify-between">
              {/* Logo */}
              <div className="flex items-center gap-2">
                <span className="text-lg font-bold">Vercel Swag Store</span>
              </div>
              {/* Navigation */}
              <nav className="flex gap-6">
                <Link
                  href="/"
                  className="text-sm font-medium text-gray-600 hover:text-gray-900"
                >
                  Home
                </Link>
                <Link
                  href="/search"
                  className="text-sm font-medium text-gray-600 hover:text-gray-900"
                >
                  Search
                </Link>
              </nav>
            </div>
          </div>
        </header>
        <main className="flex-1">{children}</main>
        <footer className="border-t bg-white">
          <div className="mx-auto max-w-7xl px-4">
            <div className="flex h-14 max-h-14 items-center text-sm text-gray-600">
              © {new Date().getFullYear()} Vercel Swag Store
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
